name: Build containers

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: ${{ github.repository }}
  TAGS: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get version
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Build runtime image from s2i image output
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }} ${{ steps.vars.outputs.version }}
          containerfiles: |
            ./Dockerfile

      # Login to Registry
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USER }}      # ${{ github.actor }} - for ghcr.io
          password: ${{ secrets.QUAY_TOKEN }}     # quay.io
      #   password: ${{ secrets.GITHUB_TOKEN }}   # ghcr.io

      - name: Push to Container Repository
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }} ${{ steps.vars.outputs.version }}
          registry: ${{ env.REGISTRY }}

      # Provenance signing image
      - name: Install cosign
        uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # v3.0.1
        with:
          cosign-release: 'v2.0.0'

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key

      - name: Sign container image with TAGS
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -y \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAGS }}
        env:
          COSIGN_PASSWORD: ""

      - name: Sign container image with VERSION
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -y \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}
        env:
          COSIGN_PASSWORD: ""